AnnonceBundle\Entity\Annonce:
    type: entity
    table: null
    repositoryClass: AnnonceBundle\Repository\AnnonceRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        vendeur:
            type: string
            length: 255
        telephone:
            type: integer
        description:
            type: text
    lifecycleCallbacks: {  }
